# Generated by Django 4.1.3 on 2022-12-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=70)),
                ('img', models.ImageField(upload_to='news/')),
                ('date', models.DateField()),
            ],
        ),
    ]
